### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by m59peacemaker** [mrapogee/babel-plugin-syntax-pipeline-operator#1]
This doesn't appear to be on npm as stated in the docs.

**Comment by m59peacemaker** [comment]
Oh, I see it's just a placeholder.

**Comment by Swizz** [comment]
Hi,

Is this usable without NPM Publishing ?

Using it with `npm install git+[...]` raise error with plugins config in `.babelrc`.

Cheers,

**Comment by mrapogee** [comment]
This is just my fork of the syntax plugin for babel I tried to get working, but it won't work until the babylon parser itself implements the pipeline-operator since babylon isn't pluggable.

**Comment by mrapogee** [comment]
You could play with this:
https://www.npmjs.com/package/babel-plugin-pipe-operator 

It just overloads the regular single `|` operator.

**Comment by Swizz** [comment]
Ow thank you, I will try it.
